# Generated by Django 3.2.8 on 2021-10-31 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id_Areas', models.AutoField(max_length=3, primary_key=True, serialize=False)),
                ('area', models.CharField(choices=[('Back', 'Backend'), ('Front', 'Frontend'), ('DevOps', 'Developmen-and-Operation')], default='Back', max_length=30)),
                ('descripcion', models.CharField(max_length=100)),
                ('conocimiento', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Padawans',
            fields=[
                ('idUser', models.AutoField(max_length=3, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Jedi',
            fields=[
                ('id', models.AutoField(max_length=3, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=100)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erona.areas')),
            ],
        ),
        migrations.CreateModel(
            name='Erona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Jedi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erona.jedi')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erona.padawans')),
            ],
        ),
    ]
