# Generated by Django 3.2.8 on 2021-10-31 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erona', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areas',
            name='id_Areas',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='jedi',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='padawans',
            name='idUser',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
