# Generated by Django 3.2.8 on 2021-10-31 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erona', '0002_auto_20211031_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id_Areas', models.AutoField(primary_key=True, serialize=False)),
                ('area', models.CharField(default='Back / Front / Devs', max_length=30)),
                ('orientado', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('conocimiento', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Padawans',
            new_name='Padawan',
        ),
        migrations.AlterField(
            model_name='jedi',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erona.area'),
        ),
        migrations.DeleteModel(
            name='Areas',
        ),
    ]
