# Generated by Django 3.2.8 on 2021-10-31 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erona', '0003_auto_20211031_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='area',
            field=models.CharField(default='Ejemplo: Back / Front / Devs', max_length=30),
        ),
        migrations.AlterField(
            model_name='area',
            name='conocimiento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='area',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='area',
            name='orientado',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
